#!/usr/bin/env python3

import sys
from PySide.QtCore import *
from PySide.QtGui import *
from functools import partial

import pyrazer
from pyrazer import ui

def main():
	try:
		ui.razer = pyrazer.Razer(enableNotifications=True)
	except pyrazer.RazerEx as e:
		print(e)
		sys.exit(1)

	# init qt application
	app = QApplication(sys.argv)
	# check if systray is available at freedesktop
	if not QSystemTrayIcon.isSystemTrayAvailable():
		print("No system tray available")
		sys.exit(1)

	# init and show applet
	applet = ui.RazerApplet();
	applet.show()

	# exec the application
	return app.exec_()

if __name__ == "__main__":
	sys.exit( main())
