#!/usr/bin/env python
#
#   Razer device commandline configuration tool
#
#   Copyright (C) 2007-2009 Michael Buesch <mb@bu3sch.de>
#
#   This program is free software; you can redistribute it and/or
#   modify it under the terms of the GNU General Public License
#   as published by the Free Software Foundation; either version 2
#   of the License, or (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.

import sys
import getopt
import time
from ConfigParser import *
from pyrazer import *

print "The razercfg commandline tool is currently broken. Please use the graphical qrazercfg tool for now."
sys.exit(1)

class OpSleep:
	def __init__(self, seconds):
		self.seconds = seconds

	def run(self, idstr):
		time.sleep(self.seconds)

class OpGetFwVer:
	def run(self, idstr):
		verTuple = razer.getFwVer(idstr)
		print "The firmware version for the mouse %s is: %d.%d" %\
			(idstr, verTuple[0], verTuple[1])

class OpGetFreq:
	def run(self, idstr):
		freqs = razer.getSupportedFreqs(idstr)
		curFreq = razer.getCurrentFreq(idstr)
		for freq in freqs:
			if freq == curFreq:
				sys.stdout.write("[%d Hz], " % freq)
			else:
				sys.stdout.write("%d Hz, " % freq)
		print ""

class OpGetRes:
	def run(self, idstr):
		resList = razer.getSupportedRes(idstr)
		curRes = razer.getCurrentRes(idstr)
		for res in resList:
			if res == curRes:
				sys.stdout.write("[%d DPI], " % res)
			else:
				sys.stdout.write("%d DPI, " % res)
		print ""

class OpPrintLeds:
	def run(self, idstr):
		leds = razer.getLeds(idstr)
		print "LEDs on mouse %s:" % idstr
		for led in leds:
			if led[1] == 0:
				state = "off"
			elif led[1] == 1:
				state = "on"
			else:
				state = "unknown"
			sys.stdout.write("%s => %s, " % (led[0], state))
		print ""

class OpSetLed:
	def __init__(self, cfgStr):
		self.cfgStr = cfgStr

	def run(self, idstr):
		cfgStr = self.cfgStr.split(":")
		try:
			newState = cfgStr[-1].lower()
			ledName = ":".join(cfgStr[:-1])
			if not ledName:
				raise ValueError()
			if newState in ["0", "off", "false"]:
				newState = False
			elif newState in ["1", "on", "true"]:
				newState = True
			else:
				raise ValueError()
		except (IndexError, ValueError):
			print "Invalid parameter to --setled option"
			exit(1)
		error = razer.setLed(idstr, ledName, newState)
		if error:
			print "Failed to set LED state. Error code is %d" % error

class OpSetRes:
	def __init__(self, resolution):
		self.resolution = resolution

	def run(self, idstr):
		try:
			resolution = int(self.resolution)
		except ValueError:
			print "Invalid parameter to --res option"
			exit(1)
		error = razer.setResolution(idstr, resolution)
		if error:
			print "Failed to set resolution to %d DPI (error=%d)" %\
				(resolution, error)

class OpSetFreq:
	def __init__(self, frequency):
		self.frequency = frequency

	def run(self, idstr):
		try:
			frequency = int(self.frequency)
		except ValueError:
			print "Invalid parameter to --freq option"
			exit(1)
		error = razer.setFrequency(idstr, frequency)
		if error:
			print "Failed to set frequency to %d Hz (error=%d)" %\
				(frequency, error)

class OpFlashFw:
	def __init__(self, filename):
		self.filename = filename

	def run(self, idstr):
		try:
			data = file(self.filename, "rb").read()
		except IOError, e:
			print "Failed to read firmware file %s: %s" %\
				(self.filename, e.strerror)
			exit(1)
		print "Flashing firmware on %s ..." % idstr
		print "!!! DO NOT DISCONNECT ANY DEVICE !!!"
		print "Sending %d bytes..." % len(data)
		error = razer.flashFirmware(idstr, data)
		if error:
			print "Failed to flash firmware (error=%d)" % error
		else:
			print "Firmware successfully flashed."

# Operations on a device
class DevOps:
	def __init__(self, idstr):
		self.idstr = idstr
		self.ops = []

	def add(self, op):
		self.ops.append(op)

	def runAll(self):
		try:
			for op in self.ops:
				op.run(self.idstr)
		except RazerEx, e:
			print "Razer device access exception:", e

def scanDevices():
	razer.rescanMice()
	mice = razer.getMice()
	for mouse in mice:
		print mouse

def exit(exitcode):
	sys.exit(exitcode)

def prVersion():
	print "Razer device configuration tool"
	print "Version", RAZER_VERSION

def usage():
	prVersion()
	print ""
	print "Usage: razercfg [OPTIONS] [-d DEV DEVOPS] [-d DEV DEVOPS]..."
	print ""
	print "-h|--help            Print this help text"
	print "-v|--version         Print the program version number"
	print "-s|--scan            Scan for devices and print the bus IDs"
	print ""
	print "-d|--device DEV      Selects the device with the bus ID \"DEV\""
	print "    Use the special value \"mouse\" for DEV to select"
	print "    the first razer mouse device found in the system."
	print "-c|--config FILE     Read the config file and apply it."
	print "    Use the special value \".\" for FILE to select the default file"
	print ""
	print "-S|--sleep SECS      Sleep SECS seconds."
	print ""
	print "Device operations (DEVOPS):"
	print "These options apply to the device that is specified with -d"
	print ""
	print "Options for mice:"
	print "-V|--fwver           Print the firmware version number"
	print "-r|--res DPI         Changes the scan resolution to DPI"
	print "-R|--getres          Prints the current and supported resolutions"
	print "-f|--freq FREQ       Changes the scan frequency to FREQ"
	print "-F|--getfreq         Prints the current and supported frequencies"
	print "-L|--leds            Print the identifiers of the LEDs on the device"
	print "-l|--setled LED:off  Toggle the LED with the identifier \"LED\" ON or OFF"
	print "-X|--flashfw FILE    Flash a firmware image to the device"

def parse_args():
	devOpsList = []
	currentDevOps = None

	try:
		(opts, args) = getopt.getopt(sys.argv[1:],
			"hvsd:r:Rf:FLl:Vc:S:X:",
			[ "help", "version", "scan", "device=", "res=",
			  "getres", "freq=", "getfreq", "leds", "setled=",
			  "fwver", "config=", "sleep=", "flashfw=", ])
	except getopt.GetoptError:
		usage()
		exit(1)

	for (o, v) in opts:
		if o in ("-h", "--help"):
			usage()
			exit(0)
		if o in ("-v", "--version"):
			prVersion()
			exit(0)
		if o in ("-s", "--scan"):
			scanDevices()
			exit(0)
		if o in ("-d", "--device"):
			if v == "mouse": # magic; select the first mouse
				razer.rescanMice()
				mice = razer.getMice()
				if not mice:
					print "No Razer mouse found on your system"
					exit(1)
				v = mice[0]
			if currentDevOps and currentDevOps.ops:
				devOpsList.append(currentDevOps)
			currentDevOps = DevOps(v)
			continue
		if o in ("-c", "--config"):
			try:
				c = Config(v)
			except IOError:
				exit(1)
			ops = currentDevOps
			if not currentDevOps:
				ops = DevOps(None)
			ops.add(OpApplyConfig(c))
			if not currentDevOps:
				devOpsList.append(ops)
		if o in ("-r", "--res"):
			if not currentDevOps:
				print "Must specify a device (-d) before -r|--res"
				exit(1)
			currentDevOps.add(OpSetRes(v))
			continue
		if o in ("-R", "--getres"):
			if not currentDevOps:
				print "Must specify a device (-d) before -R|--getres"
				exit(1)
			currentDevOps.add(OpGetRes())
			continue
		if o in ("-f", "--freq"):
			if not currentDevOps:
				print "Must specify a device (-d) before -f|--freq"
				exit(1)
			currentDevOps.add(OpSetFreq(v))
			continue
		if o in ("-F", "--getfreq"):
			if not currentDevOps:
				print "Must specify a device (-d) before -F|--getfreq"
				exit(1)
			currentDevOps.add(OpGetFreq())
			continue
		if o in ("-L", "--leds"):
			if not currentDevOps:
				print "Must specify a device (-d) before -L|--leds"
				exit(1)
			currentDevOps.add(OpPrintLeds())
			continue
		if o in ("-l", "--setled"):
			if not currentDevOps:
				print "Must specify a device (-d) before -l|--setled"
				exit(1)
			currentDevOps.add(OpSetLed(v))
			continue
		if o in ("-V", "--fwver"):
			if not currentDevOps:
				print "Must specify a device (-d) before -V|--fwver"
				exit(1)
			currentDevOps.add(OpGetFwVer())
			continue
		if o in ("-S", "--sleep"):
			ops = currentDevOps
			if not currentDevOps:
				ops = DevOps(None)
			try:
				v = float(v)
			except ValueError:
				print "Value for -S|--sleep must be a floating point value"
				exit(1)
			ops.add(OpSleep(v))
			if not currentDevOps:
				devOpsList.append(ops)
			continue
		if o in ("-X", "--flashfw"):
			if not currentDevOps:
				print "Must specify a device (-d) before -X|--flashfw"
				exit(1)
			currentDevOps.add(OpFlashFw(v))
			continue
	if currentDevOps and currentDevOps.ops:
		devOpsList.append(currentDevOps)
	if not devOpsList:
		usage()
		exit(1)
	return devOpsList

def main():
	try:
		global razer

		razer = Razer()

		devOpsList = parse_args()
		if not devOpsList:
			exit(1)
		for devOps in devOpsList:
			devOps.runAll()
	except RazerEx, e:
		print e
	exit(0)

if __name__ == "__main__":
	main()
